# 必需包
required = ["github.com/gin-gonic/gin"]
# 忽略包
ignored = ["golang.org/x/sys/unix"]
# 项目元数据
[metadata]
homepage = "https://github.com/ealpha"
license = "MIT"
owners_name_1 = "ealpha"
owners_email_1 = "ealpha@gmail.com"
owners_homepage_1 = "https://github.com/ealpha"

# 约束条件
[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "=1.2"

[[constraint]]
  name = "github.com/go-xorm/xorm"
  version = "0.6.6"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.35.0"
